---
- name: SSH Config
  hosts: all
  become: true
  tasks:
    - name: Add sshd_config
      copy:
        src: ../ssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0600

- name: Fix System Time
  hosts: all
  become: true
  tasks:
    - name: enable timesyncd
      systemd:
        name: systemd-timesyncd
        enabled: yes
        state: started
