---
- name: SSH Config
  hosts: all
  become: true
  tasks:
    - name: add sshd_config
      copy:
        src: ../ssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0600

- name: Fix System Time
  hosts: all
  become: true
  tasks:
    - name: enable timesyncd
      systemd:
        name: systemd-timesyncd
        enabled: yes
        state: started

- name: Setup Shell
  hosts: all
  become: true
  tasks:
    - name: make /data writable by main user so saving bash history works
      file:
        path: /data
        owner: slang
        group: users
        mode: 0755
        state: directory
    - name: add .bashrc
      copy:
        src: ../shell/.bashrc
        dest: /home/slang/.bashrc
        owner: slang
        group: users
        mode: 0644
